// react/07_learn_reactrouter/src/pages/Home.jsx
import React, { PureComponent } from 'react';
import { Link, Outlet } from 'react-router-dom';

export class Home extends PureComponent {
  constructor(props) {
    super(props);
    this.navigateTo = this.navigateTo.bind(this);
  }

  navigateTo(path) {
    console.log(path);
  }

  render() {
    return (
      <div>
        <h2>Home</h2>
        <Link to='/home/recommend'>推荐</Link>
        <Link to='/home/ranking'>排行榜</Link>
        <button onClick={() => this.navigateTo('/home/songList')}>歌单</button>
        {/* 子路由的占位符 */}
        <Outlet />
      </div>
    );
  }
}

export default Home;

// vue3/vue3-webpack-router/src/views/home.vue
<template>
  <div>home</div>
  <h1>{{ $route.query }}</h1>

  <router-link to="/home/recommend">推荐</router-link>
  <router-link to="/home/ranking">排行榜</router-link>
  <router-link to="/home/vip">vip</router-link>
  <router-view></router-view>

  <button @click="logout">退出登录</button>
</template>

<script setup>
import { useRouter } from 'vue-router';

const router = useRouter();

console.log(router.meta);

function logout() {
  localStorage.removeItem('token');
  console.log(router);
  router.push('/login');
}
</script>

<style scoped>
.router-link-active {
  color: red;
  font-size: 30px;
}
</style>
